# =============================================================
#  GitHub CommitView for Rainmeter
#  FetchCommits.ps1
#  Fetches latest commits per repo and generates CommitView.ini
# =============================================================
param([string]$SkinPath = '')

if (-not $SkinPath) { $SkinPath = Split-Path -Parent $MyInvocation.MyCommand.Path }
$Log = Join-Path $SkinPath 'debug_commits.log'

[System.IO.File]::WriteAllText($Log, '', [System.Text.UTF8Encoding]::new($false))
function L($m) {
    [System.IO.File]::AppendAllText($Log, "[$(Get-Date -f HH:mm:ss)] $m`r`n", [System.Text.UTF8Encoding]::new($false))
}
L '=== CommitView v1.2 ==='

$OutputIni = Join-Path $SkinPath 'CommitView.ini'

# ------------------------------------------------------------------
# Parse Settings.inc
# ------------------------------------------------------------------
$Token = ''; $Repo1 = ''; $Repo2 = ''; $Repo3 = ''; $AutoRefreshMin = 0

$sf = Join-Path (Split-Path $SkinPath -Parent) 'Settings.inc'
if (Test-Path $sf) {
    foreach ($line in [System.IO.File]::ReadAllLines($sf, [System.Text.UTF8Encoding]::new($true))) {
        if ($line -match '^GitHubToken\s*=\s*(.+)$')      { $Token          = $Matches[1].Trim() }
        if ($line -match '^Repo1\s*=\s*(.+)$')            { $Repo1           = $Matches[1].Trim() }
        if ($line -match '^Repo2\s*=\s*(.+)$')            { $Repo2           = $Matches[1].Trim() }
        if ($line -match '^Repo3\s*=\s*(.+)$')            { $Repo3           = $Matches[1].Trim() }
        if ($line -match '^AutoRefreshMin\s*=\s*(\d+)$')  { $AutoRefreshMin  = [int]$Matches[1] }
    }
    L 'Settings.inc loaded'
} else {
    L 'WARNING: Settings.inc not found'
}
if ($AutoRefreshMin -gt 0 -and $AutoRefreshMin -lt 1) { $AutoRefreshMin = 1 }
L "Token=$(if($Token){'set'}else{'NOT SET'})  Repo1=$Repo1  Repo2=$Repo2  Repo3=$Repo3  AutoRefreshMin=$AutoRefreshMin"

if ($Token -eq '' -or $Token -eq 'ghp_your_token_here') { L 'ERROR: GitHubToken not set'; exit 1 }

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
$Headers = @{
    Authorization = "Bearer $Token"
    'User-Agent'  = 'Rainmeter-GitHubGrass/1.0'
}

function Get-RelativeTime($dateStr) {
    $diff = (Get-Date).ToUniversalTime() - [datetime]::Parse($dateStr).ToUniversalTime()
    if    ($diff.TotalMinutes -lt 60) { return "$([int]$diff.TotalMinutes)m ago" }
    elseif($diff.TotalHours   -lt 24) { return "$([int]$diff.TotalHours)h ago"   }
    elseif($diff.TotalDays    -lt 7)  { return "$([int]$diff.TotalDays)d ago"    }
    else                               { return "$([int]($diff.TotalDays/7))w ago" }
}

# ------------------------------------------------------------------
# Fetch up to 10 commits per repo
# ------------------------------------------------------------------
$Rows = [System.Collections.Generic.List[hashtable]]::new()

foreach ($repo in @($Repo1, $Repo2, $Repo3)) {
    if ($repo -eq '') { continue }
    L "Fetching: $repo"
    try {
        $url     = 'https://api.github.com/repos/' + $repo + '/commits?per_page=10'
        $commits = Invoke-RestMethod -Uri $url -Headers $Headers -ErrorAction Stop
        $name    = ($repo -split '/')[1]
        $ghBase  = 'https://github.com/' + $repo
        foreach ($c in $commits) {
            $msg = ($c.commit.message -split "`n")[0].Trim()
            $rel = Get-RelativeTime $c.commit.author.date
            $commitUrl = $ghBase + '/commit/' + $c.sha
            $Rows.Add(@{ name=$name; msg=$msg; time=$rel; url=$commitUrl })
        }
        L "  OK  $($commits.Count) commits"
    } catch {
        L ('  FAIL: ' + $_.Exception.Message)
    }
}

L ("Total rows: " + $Rows.Count)

# ------------------------------------------------------------------
# Layout constants
# ------------------------------------------------------------------
$WW        = 500
$HeaderH   = 32
$Padding   = 14
$RowPadT   = 8     # 헤더 아래 상단 패딩
$RowPadB   = 8     # 하단 패딩
$RowH      = 24
$RepoColW  = 110
$MsgColX   = 132   # Padding + RepoColW + 8
$TimeColW  = 68
$TimeColX  = $WW - $Padding - $TimeColW   # = 418 (우측 고정)
$MsgColW   = $TimeColX - $MsgColX - 24   # gap 24px → = 262

$activeRows = $Rows.Count
$WH = $HeaderH + $RowPadT + $activeRows * $RowH + $RowPadB

$cBG     = '13,17,23,240'
$cStroke = '48,54,61,255'
$cBlue   = '55,115,185,255'

# ------------------------------------------------------------------
# Generate CommitView.ini
# ------------------------------------------------------------------
$lines = [System.Collections.Generic.List[string]]::new()
function W($s) { $lines.Add($s) }

W ('; CommitView - Generated ' + (Get-Date -f 'yyyy-MM-dd HH:mm'))
W '; DO NOT EDIT - regenerated by run_commits.bat'
W ''
W '[Rainmeter]'
W 'Update=60000'
W 'AccurateText=1'
W ''
W '[Variables]'
W ('SkinFolder=' + $SkinPath)
W ''

# Background
W '[MeterBG]'
W 'Meter=Shape'
W 'X=0'
W 'Y=0'
W ('Shape=Rectangle 0,0,' + $WW + ',' + $WH + ',8 | Fill Color ' + $cBG + ' | StrokeWidth 1 | Stroke Color ' + $cStroke)
W ''

# Header bar
W '[MeterHeader]'
W 'Meter=Shape'
W 'X=0'
W 'Y=0'
W ('Shape=Rectangle 0,0,' + $WW + ',' + $HeaderH + ',8,0,0,0 | Fill Color ' + $cBlue + ' | StrokeWidth 0')
W ''

# Header label  (StringAlign 없이 수동 Y 중앙 배치)
$headerLabelY = [int](($HeaderH - 11) / 2)   # FontSize=8 Segoe UI ≈ 11px
W '[MHeaderLabel]'
W 'Meter=String'
W "X=$Padding"
W "Y=$headerLabelY"
W 'W=200'
W 'H=20'
W 'Text=COMMITS'
W 'FontColor=255,255,255,220'
W 'FontSize=8'
W 'FontFace=Segoe UI'
W 'FontWeight=700'
W 'AntiAlias=1'
W ''

# Commit rows
$prevName = ''
for ($i = 0; $i -lt $Rows.Count; $i++) {
    $row    = $Rows[$i]
    $name   = $row.name
    $msg    = $row.msg
    $time   = $row.time
    $y      = $HeaderH + $RowPadT + $i * $RowH
    $action = '["' + $row.url + '"]'

    # Dim repeated repo names for visual grouping
    $nameColor = if ($name -eq $prevName) { '100,100,100,180' } else { '200,200,200,255' }
    $prevName  = $name

    W "[MRow${i}Name]"
    W 'Meter=String'
    W "X=$Padding"
    W "Y=$y"
    W "W=$RepoColW"
    W "H=$RowH"
    W "Text=$name"
    W "FontColor=$nameColor"
    W 'FontSize=9'
    W 'FontFace=Segoe UI'
    W 'AntiAlias=1'
    W 'ClipString=2'
    W "LeftMouseUpAction=$action"
    W ''

    W "[MRow${i}Msg]"
    W 'Meter=String'
    W "X=$MsgColX"
    W "Y=$y"
    W "W=$MsgColW"
    W "H=$RowH"
    W "Text=$msg"
    W 'FontColor=139,148,158,255'
    W 'FontSize=9'
    W 'FontFace=Segoe UI'
    W 'AntiAlias=1'
    W 'ClipString=2'
    W "LeftMouseUpAction=$action"
    W ''

    W "[MRow${i}Time]"
    W 'Meter=String'
    W "X=$TimeColX"
    W "Y=$y"
    W "W=$TimeColW"
    W "H=$RowH"
    W "Text=$time"
    W 'FontColor=88,96,105,200'
    W 'FontSize=8'
    W 'FontFace=Segoe UI'
    W 'AntiAlias=1'
    W "LeftMouseUpAction=$action"
    W ''
}

# Auto-refresh measure (hidden, fires every AutoRefreshMin minutes)
if ($AutoRefreshMin -ge 1) {
    W '[MAutoRefresh]'
    W 'Measure=Calc'
    W 'Formula=0'
    W "UpdateDivider=$AutoRefreshMin"
    W ('OnUpdateAction=["wscript.exe" "#CURRENTPATH#launcher_commits.vbs"]')
    W ''
}

# Refresh button - Shape circle + R label
$btnCX = $WW - $Padding - 8   # 원 중심 X
$btnCY = [int]($HeaderH / 2)  # 원 중심 Y (헤더 수직 중앙)
W '[MRefreshBtn]'
W 'Meter=Shape'
W "X=$($btnCX - 8)"
W "Y=$($btnCY - 8)"
W 'W=16'
W 'H=16'
W ('Shape=Ellipse 8,8,7 | Fill Color 255,255,255,30 | StrokeWidth 1 | Stroke Color 255,255,255,120')
W ('LeftMouseUpAction=["wscript.exe" "#CURRENTPATH#launcher_commits.vbs"]')
W 'ToolTipText=Click to reload commits'
W 'MouseOverAction=[!SetOption MRefreshBtn Shape "Ellipse 8,8,7 | Fill Color 255,255,255,60 | StrokeWidth 1 | Stroke Color 255,255,255,180"][!UpdateMeter MRefreshBtn][!Redraw]'
W 'MouseLeaveAction=[!SetOption MRefreshBtn Shape "Ellipse 8,8,7 | Fill Color 255,255,255,30 | StrokeWidth 1 | Stroke Color 255,255,255,120"][!UpdateMeter MRefreshBtn][!Redraw]'
W ''
W '[MRefreshLabel]'
W 'Meter=String'
W "X=$($btnCX - 4)"
W "Y=$($btnCY - 5)"
W 'W=10'
W 'H=12'
W ('Text=' + [char]0xE5D5)
W 'FontColor=255,255,255,200'
W 'FontSize=14'
W 'FontFace=Material Icons'
W 'AntiAlias=1'
W ('LeftMouseUpAction=["wscript.exe" "#CURRENTPATH#launcher_commits.vbs"]')
W 'ToolTipText=Click to reload commits'
W ''

# ------------------------------------------------------------------
# Save with UTF-8 BOM
# ------------------------------------------------------------------
$content = [string]::Join("`r`n", $lines)
[System.IO.File]::WriteAllText($OutputIni, $content, [System.Text.UTF8Encoding]::new($true))
L ('Saved: ' + $OutputIni + '  rows=' + $activeRows + '  WH=' + $WH)

# ------------------------------------------------------------------
# Trigger Rainmeter skin refresh
# ------------------------------------------------------------------
$config  = (Split-Path (Split-Path $SkinPath -Parent) -Leaf) + '\' + (Split-Path $SkinPath -Leaf)
$iniFile = 'CommitView.ini'
$rmExe   = "$env:ProgramFiles\Rainmeter\Rainmeter.exe"
if (-not (Test-Path $rmExe)) { $rmExe = "${env:ProgramFiles(x86)}\Rainmeter\Rainmeter.exe" }
if (Test-Path $rmExe) {
    Start-Process $rmExe -ArgumentList "!Refresh `"$config`" `"$iniFile`""
    L "Rainmeter refresh triggered: $config\$iniFile"
} else {
    L 'WARNING: Rainmeter.exe not found'
}

L '=== DONE ==='
